#!/usr/bin/env bash
# Scripts Installs nginx server

sudo apt-get -y update
sudo apt-get -y install nginx
# allow nginx http on firewall
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
