#!/usr/bin/env bash
# Scripts Installs nginx server

apt-get -y update
apt-get -y install nginx
# allow nginx http on firewall
sudo ufw allow "Nginx HTTP"
echo "Hello World!" > /var/www/html/index.html
# restart nginx
service nginx restart
