#!/usr/bin/env bash
# Script that installs Nginx server and redirects /redirect_me
sudo apt-get -y iupdate
sudo apt-get -y install nginx

sudo chown -R "$USER":"$USER" /var/www/html/index.nginx-debian.html
sudo chown -R "$USER":"$USER" /etc/nginx/sites-available/default

echo "Hello World!" > /var/www/html/index.nginx-debian.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/codestronomer permanent;/" /etc/nginx/sites-available/default
sudo service nginx restart
