#!/usr/bin/env bash
# A bash script that displays "Best School" 10 time also "Hi"
#+ on the 9th iteration
i=1
while [ $i -ne 11 ]
do
	echo "Best School"
	if [ $i -eq 9 ]
		then 
			echo "Hi"
	fi
	i=$(( i + 1))
done
