#!/usr/bin/env bash
# Bash script displays the content of the current directory
#+ in a list format
#+ where only the apart of the name after the first dash is displayed
for i in *
do
	echo "$i" | cut -f 2- -d '_'
done
