#!/usr/bin/env bash
# scripts confiure container to run 'nginx' as nginx user
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf
sed -i "s/80/8080/g" /etc/nginx/sites-available/default
chown nginx:nginx /etc/nginx/nginx.conf
chown u+rwx /etc/nginx/nginx.conf
chown nginx:nginx /usr/sbin/nginx
service apache2 stop
pkill apache2
su -c "service nginx restart" nginx
